# Generated by Django 2.2.7 on 2019-11-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='hostname',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
