# Generated by Django 2.2.7 on 2019-11-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_app', '0002_visitor_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='check_out',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
